apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: arvancnt-rabbitmq
  labels:
    app: arvancnt-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvancnt-rabbitmq
  template:
    metadata:
      labels:
        app: arvancnt-rabbitmq
    spec:
      imagePullSecrets:
      - name: arvan-registry
      containers:
      - image: reg.arvancloud.com:5000/rabbitmq:latest
        name: arvancnt-rabbitmq
         
---
kind: Service
apiVersion: v1
metadata:
  name: arvancnt-rabbitmq
spec:
  selector:
    app: arvancnt-rabbitmq
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: rtmp
    protocol: TCP
    port: 1935
    targetPort: 1935
  - name: ampq
    port: 5672
    targetPort: 5672
  clusterIP: 10.96.184.243
  externalIPs:
  -  10.24.52.243
