apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: arvancnt-sheltie
  labels:
    app: arvancnt-sheltie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvancnt-sheltie
  template:
    metadata:
      labels:
        app: arvancnt-sheltie
    spec:
      serviceAccountName: sheltie-builder
      automountServiceAccountToken: false
      hostNetwork: true
      imagePullSecrets:
      - name: arvan-registry
      containers:
      - image: khallaghi/sheltie:0.3.5
        name: arvancnt-sheltie
        volumeMounts:
        - name: automation-files
          mountPath: /root/automation 
      volumes:
      - name: automation-files
        hostPath:
          path: /root/automation
          type: Directory

---
kind: Service
apiVersion: v1
metadata:
  name: arvancnt-sheltie
spec:
  selector:
    app: arvancnt-sheltie
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: rtmp
    protocol: TCP
    port: 1935
    targetPort: 1935
  - name: ampq
    port: 5672
    targetPort: 5672
  clusterIP: 10.96.184.242
  externalIPs:
  -  10.24.52.241
